import {withoutM92Presentation} from './helpers/m92-presentation-seams.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {arenaSurfaces,ARENA_ART} from '../src/arena-art.js';import {MATCH_MAP,CAMP_SITES} from '../src/match-data.js';import {boot} from './helpers/game-browser.js';
test('M8.6 preserves all gameplay and arena data exactly against playtested M8.5',()=>{for(const name of ['main','game-ux','config','simulation','combat','combat-core','combat-data','riven-data','summoners','advanced-actions','returning-weapons','modifiers','match','match-data','match-bots','wilderness','crownfall-rules','camera','input','ability-input','combat-view','combat-feedback','match-ui','hud-presentation','ui'])assert.equal(withoutM92Presentation(fs.readFileSync('src/'+name+'.js','utf8'),name),execFileSync('git',['show','c9c1c0b:src/'+name+'.js'],{encoding:'utf8'}),name);});
test('art is bounded, mapped to exact existing centers, six supplied textures, and no map mutation',()=>{const before=JSON.stringify(MATCH_MAP),s=arenaSurfaces(MATCH_MAP);assert.equal(JSON.stringify(MATCH_MAP),before);assert.equal(s.length,14);assert.equal(new Set(s.map(x=>x.asset)).size,6);for(const p of s){assert.ok(Math.abs(p.x)+p.w/2<=MATCH_MAP.width/2);assert.ok(Math.abs(p.z)+p.d/2<=MATCH_MAP.depth/2);}assert.ok(s.filter(p=>p.asset==='goal').every(p=>[MATCH_MAP.lane.goalA,MATCH_MAP.lane.goalB].includes(p.x)));for(const c of CAMP_SITES)assert.ok(s.some(p=>p.x===c.x&&p.z===c.z&&p.asset===(c.type==='damage'?'major':'minor')));for(const a of ARENA_ART.assets)assert.ok(fs.statSync('dist/assets/arena/'+a+'.jpeg').size>1000);assert.equal(ARENA_ART.maxTextureSize,1024);});
const open=b=>{b.click('open-settings');b.click('edit-controls');b.tick(2);};
test('collapsed editor preserves ongoing drag, all seven handles, selection and inert gameplay',()=>{for(const [w,h]of [[568,320],[844,390],[932,430]]){const b=boot(w,h);open(b);const state=JSON.stringify(b.debug().match),handles=b.el('layout-handles').children,p=handles[0];p.emit('pointerdown',{pointerId:7,clientX:60,clientY:200});b.click('layout-collapse');assert.equal(b.el('layout-dock').hidden,true);assert.equal(b.el('layout-reopen').hidden,false);assert.equal(handles.length,7);assert.ok(p.hasPointerCapture(7));p.emit('pointermove',{pointerId:7,clientX:130,clientY:150});const x=b.el('layout-x').value;p.emit('pointerup',{pointerId:7});b.tick(120);assert.equal(JSON.stringify(b.debug().match),state);b.click('layout-reopen');assert.equal(b.el('layout-dock').hidden,false);assert.equal(b.el('layout-x').value,x);assert.equal(b.el('layout-handles').children.length,7);b.click('layout-cancel');assert.equal(b.debug().ux,'settings');assert.deepEqual(b.errors,[]);}});
test('collapse/reopen preserves unsaved edits, Save persistence, Cancel and confirmed Reset',()=>{let value=null;const store={getItem:()=>value,setItem:(_,v)=>value=v},b=boot(844,390,store);open(b);b.el('layout-x').oninput({target:{value:'.24'}});b.click('layout-collapse');b.click('layout-reopen');b.click('layout-save');assert.equal(JSON.parse(value).controls.move.x,.24);const saved=value;b.click('edit-controls');b.el('layout-x').oninput({target:{value:'.35'}});b.click('layout-collapse');b.click('layout-reopen');b.click('layout-cancel');assert.equal(value,saved);b.click('edit-controls');b.click('layout-reset');b.click('layout-collapse');b.click('layout-reopen');assert.equal(b.el('layout-reset').textContent,'CONFIRM RESET');b.click('layout-reset');b.click('layout-save');assert.deepEqual(JSON.parse(value).controls,{});assert.deepEqual(b.errors,[]);});
test('terrain renderer reuses six capped textures and a single mesh across matches and frames',async()=>{
 const {ArenaArt}=await import('../src/arena-art.js');let textures=0,buffers=0,draws=0;const oldImage=globalThis.Image,oldDocument=globalThis.document;
 globalThis.Image=class{constructor(){this.width=1254;this.height=1254;}set src(v){this.onload();}};
 globalThis.document={createElement:()=>({getContext:()=>({drawImage(){}})})};
 const gl=new Proxy({}, {get:(_,k)=>k==='createTexture'?()=>{textures++;return {};}:k==='createBuffer'?()=>{buffers++;return {};}:k==='drawArrays'?()=>draws++:k==='getParameter'?()=>4096:k==='getShaderParameter'||k==='getProgramParameter'?()=>true:/^[A-Z_0-9]+$/.test(k)?1:()=>({})});
 try{const a=new ArenaArt(gl);for(let i=0;i<1000;i++)a.render(MATCH_MAP,{x:0,z:0},2);assert.equal(textures,6);assert.equal(buffers,1);assert.equal(draws,14000);assert.equal(a.failed.length,0);assert.equal(a.surfaces.length,14);}finally{if(oldImage===undefined)delete globalThis.Image;else globalThis.Image=oldImage;if(oldDocument===undefined)delete globalThis.document;else globalThis.document=oldDocument;}
});