import test from 'node:test';import assert from 'node:assert/strict';
import {CombatFeedback,FEEDBACK_CONFIG} from '../src/combat-feedback.js';
import {CombatSimulation} from '../src/combat.js';import {KIT} from '../src/combat-data.js';import {SUMMONERS} from '../src/summoners.js';import {CrownfallMatch} from '../src/match.js';import {CrownfallBot} from '../src/match-bots.js';import {makeCombatant} from '../src/combat-core.js';
const idle={moveX:0,moveZ:0,aiming:false};
function setup(id='kit-asher'){const def=SUMMONERS.find(s=>s.definition.id===id),sim=new CombatSimulation(def.definition,def.training);sim.player.x=sim.player.z=0;sim.targets=[];const feedback=new CombatFeedback();feedback.bind(sim);feedback.update(sim);return {sim,feedback};}
function enemy(x=2,z=0){return {...makeCombatant('target',2,'summoner',5000,.45),x,z,spawn:{x,z}};}
function advance(sim,feedback,n=60){for(let i=0;i<n;i++){sim.step(idle);feedback.update(sim);}}
test('Kit basic has 42% shorter depth, unchanged angle, damage, cadence; close-mid hit but old reach misses',()=>{const {sim,feedback}=setup();const a=KIT.abilities[0];assert.equal(a.range,2.8);assert.equal(a.angle,Math.PI*.65);assert.equal(a.cooldown,.55);assert.deepEqual(a.damage,[110,150]);const near=enemy(2.5),far={...enemy(4),id:'far'},side={...enemy(1.5,1.5),id:'side'};sim.targets=[near,far,side];sim.cast('whip',Math.PI/2);assert.equal(near.health,4890);assert.equal(side.health,4890);assert.equal(far.health,5000);assert.equal(feedback.numbers.length,2);});
test('a cone miss gives no hit effect, no hit sound hook and a brief local miss notice',()=>{const {sim,feedback}=setup();const events=[];feedback.subscribe(e=>events.push(e));sim.targets=[enemy(5)];sim.cast('whip',Math.PI/2);advance(sim,feedback,4);assert.equal(feedback.effects.filter(e=>e.kind==='hit').length,0);assert.equal(events.filter(e=>e.type==='hit').length,0);assert.match(feedback.notice.text,/missed/);advance(sim,feedback,120);assert.ok(feedback.notice.expires<sim.now);});
test('rapid multihits aggregate actual damage and bounded effect buffers expire without growing',()=>{const {sim,feedback}=setup('riven'),target=enemy();sim.targets=[target];const a=sim.ability('elf-dance');for(let i=0;i<5;i++)sim.damage(target,48,sim.player,{ability:a});assert.equal(feedback.numbers.length,1);assert.equal(feedback.numbers[0].amount,240);assert.equal(feedback.effects.filter(e=>e.kind==='hit').length,1);for(let i=0;i<200;i++)feedback.emit({type:'hit',time:sim.now,target:{...target,id:'target'+i},source:sim.player,amount:1,ability:a});assert.ok(feedback.effects.length<=FEEDBACK_CONFIG.maxEffects);assert.ok(feedback.numbers.length<=FEEDBACK_CONFIG.maxNumbers);advance(sim,feedback,70);assert.equal(feedback.numbers.length,0);assert.equal(feedback.effects.length,0);});
test('hit events distinguish basic, skill, Ultimate and isolate failing audio subscribers',()=>{const {sim,feedback}=setup();const events=[],off=feedback.subscribe(e=>events.push(e));feedback.subscribe(()=>{throw new Error('sound unavailable');});const target=enemy();for(const id of ['whip','ring','dragon'])sim.damage(target,10,sim.player,{ability:sim.ability(id)});assert.deepEqual(events.filter(e=>e.type==='hit').map(e=>e.tier),[1,2,3]);assert.equal(target.health,4970);off();sim.damage(target,10,sim.player);assert.equal(events.length,3);});
test('Death Scream emits source-centered rings at exact existing radius and applies existing stun/damage',()=>{const {sim,feedback}=setup('riven');const target=enemy(4);sim.targets=[target];const a=sim.ability('death-scream');sim.cast(a.id);const fx=feedback.effects.find(e=>e.kind==='scream');assert.deepEqual([fx.x,fx.z,fx.range],[0,0,6]);assert.equal(target.health,4945);assert.equal(target.statuses.stun,1.3);assert.equal(a.cooldown,18);});
test('missed Predatory Combo emits no strikes and keeps existing full cooldown',()=>{const {sim,feedback}=setup('set');sim.cast('predatory',Math.PI/2);advance(sim,feedback,30);assert.equal(sim.advanced.sequence,null);assert.equal(feedback.numbers.length,0);assert.match(feedback.notice.text,/missed/);assert.ok(sim.cooldowns.remaining('predatory',sim.now)>7);});
test('camp reward, reset, death and permanent elimination feedback observe current rules',()=>{const m=new CrownfallMatch('kit-asher',{countdownSeconds:0,startingTickets:0}),f=new CombatFeedback();m.start();f.bind(m.human);f.update(m.human);const events=[];f.subscribe(e=>events.push(e));const camp=m.wilderness.camps[0];m.human.damage(camp,99999,m.human.player);f.update(m.human);assert.ok(events.some(e=>e.type==='camp-defeated'));assert.ok(events.some(e=>e.type==='buff-acquired'));assert.match(f.notice.text,/MOBILITY acquired/);const p=m.entities[3];p.finalRespawnAvailable=false;m.human.damage(p,99999,m.human.player);assert.ok(p.eliminated);assert.ok(events.some(e=>e.type==='elimination'));const reset=m.wilderness.camps[1];reset.health-=50;f.update(m.human);reset.health=reset.maxHealth;f.update(m.human);assert.ok(events.some(e=>e.type==='camp-reset'));});
test('Ultimate-ready hook triggers once per transition, consumes normally, and resets on new match',()=>{const m=new CrownfallMatch('kit-asher',{countdownSeconds:0}),f=new CombatFeedback();m.start();f.bind(m.human);f.update(m.human);const events=[];f.subscribe(e=>events.push(e));m.human.player.ultimateMeter=100;for(let i=0;i<30;i++)f.update(m.human);assert.equal(events.filter(e=>e.type==='ultimate-ready').length,1);m.human.cast('dragon');f.update(m.human);assert.equal(m.human.player.ultimateMeter,0);assert.equal(f.ready,false);f.bind(new CrownfallMatch().human);assert.equal(f.effects.length,0);assert.equal(f.numbers.length,0);assert.equal(f.states.size,0);});
test('three complete bot matches are identical with feedback enabled/disabled, including tickets, territory, camps and stances',()=>{for(const selected of ['kit-asher','set','riven']){const plain=new CrownfallMatch(selected,{countdownSeconds:0}),shown=new CrownfallMatch(selected,{countdownSeconds:0}),f=new CombatFeedback();for(const m of [plain,shown]){m.actors[0].bot=new CrownfallBot(3);m.start();}f.bind(shown.human);let ticks=0;while(!plain.rules.result&&ticks<18100){plain.step(idle);shown.step(idle);f.update(shown.human);ticks++;}assert.ok(plain.rules.result);assert.deepEqual(shown.snapshot(),plain.snapshot());assert.deepEqual(shown.actors.map(a=>a.sim.stance),plain.actors.map(a=>a.sim.stance));assert.ok(f.effects.length<=48);assert.ok(f.numbers.length<=18);}});