import test from 'node:test';import assert from 'node:assert/strict';import {boot} from './helpers/game-browser.js';
import {LAYOUT_CONFIG,validateLayout,defaultLayout,loadLayout,layoutBounds} from '../src/control-layout.js';
const storage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};};
const editor=b=>{b.click('open-settings');b.click('edit-controls');b.tick(3);assert.equal(b.debug().ux,'control-editor');};
const select=(b,slot)=>b.el('layout-selected').onchange({target:{value:slot}});
const change=(b,prop,value)=>b.el('layout-'+prop).oninput({target:{value:String(value)}});
const launch=(b,riven=true)=>{b.click('settings-back');b.click('play');if(riven)b.el('summoner-cards').children[2].onclick();b.click('confirm-summoner');b.tick(185);assert.equal(b.debug().ux,'active');};
const press=(el,id)=>{const r=el.getBoundingClientRect();el.emit('pointerdown',{pointerId:id,clientX:r.left+r.width/2,clientY:r.top+r.height/2});el.emit('pointerup',{pointerId:id});};
function customize(b){editor(b);const proxy=b.el('layout-handles').children.find(p=>p.dataset.control==='move');proxy.emit('pointerdown',{pointerId:9,clientX:72,clientY:328});proxy.emit('pointermove',{pointerId:9,clientX:100,clientY:240});proxy.emit('pointerup',{pointerId:9});select(b,'move');change(b,'x',.12);change(b,'y',.62);select(b,'skill1');change(b,'x',.38);change(b,'y',.75);select(b,'ultimate');change(b,'x',.59);change(b,'y',.72);select(b,'basic');change(b,'scale',1.2);select(b,'skill2');change(b,'opacity',.5);select(b,'special');change(b,'x',.79);change(b,'y',.46);assert.equal(b.el('layout-save').disabled,false);b.click('layout-save');assert.equal(b.debug().ux,'settings');}
test('malformed, partial, outdated and inaccessible persistence safely fall back to exact CSS defaults',()=>{
 const good={version:1,controls:{move:{x:.1,y:.8,scale:1,opacity:.9}}};assert.deepEqual(validateLayout(good),good);for(const bad of [null,{},[],{version:2,controls:{}},{version:1,controls:{move:{x:0}}},{version:1,controls:{move:{x:.5,y:3,scale:1,opacity:1}}},{version:1,controls:{move:{x:.5,y:.5,scale:.01,opacity:0}}}])assert.deepEqual(validateLayout(bad),defaultLayout());assert.deepEqual(loadLayout({getItem:()=>'{broken'}),defaultLayout());assert.deepEqual(loadLayout({getItem(){throw Error();}}),defaultLayout());
});
test('editor freezes all match state, clears gameplay input and Cancel restores prior layout without saving',()=>{
 const store=storage(),b=boot(844,390,store);editor(b);const snapshot=JSON.stringify(b.debug().match);b.window.emit('keydown',{code:'KeyW'});b.window.emit('keydown',{code:'KeyQ'});b.tick(120);assert.equal(JSON.stringify(b.debug().match),snapshot);assert.equal(b.debug().input.moveZ,0);select(b,'move');change(b,'x',.2);change(b,'scale',1.2);b.click('layout-cancel');assert.equal(b.debug().ux,'settings');assert.equal(store.getItem(LAYOUT_CONFIG.key),null);assert.equal(b.el('layout-handles').children.length,0);assert.equal(b.el('control-editor').hidden,true);assert.equal(b.el('move-control').style.position,'');assert.deepEqual(b.errors,[]);
});
test('unusual layout saves normalized positions, scale, opacity and STANCE across reload, menu and rematch',()=>{
 const store=storage(),b=boot(844,390,store);customize(b);const saved=JSON.parse(store.getItem(LAYOUT_CONFIG.key));assert.equal(saved.controls.move.x,.12);assert.equal(saved.controls.move.y,.62);assert.equal(saved.controls.basic.scale,1.2);assert.equal(saved.controls.skill2.opacity,.5);assert.equal(saved.controls.special.x,.79);
 b.el('setting-timeLimitSeconds').value='5';launch(b);let buttons=b.el('ability-bar').children;assert.equal(buttons[0].style.transform,'scale(1.2)');assert.equal(buttons[2].style.opacity,'0.5');const state=JSON.stringify(b.debug().match);const moved=b.el('move-stick').getBoundingClientRect();b.el('move-stick').emit('pointerdown',{pointerId:1,clientX:moved.left+moved.width,clientY:moved.top+moved.height/2});const aim=b.el('aim-stick').getBoundingClientRect();b.el('aim-stick').emit('pointerdown',{pointerId:2,clientX:aim.left+aim.width/2,clientY:aim.top});assert.ok(b.debug().input.moveX>0);assert.equal(b.debug().input.aiming,true);press(buttons[4],3);b.tick(1);assert.equal(b.debug().combat.stance,'pulse');assert.ok(b.debug().input.moveX>0);assert.equal(b.debug().input.aiming,true);buttons=b.el('ability-bar').children;assert.ok(buttons[4].style.left);press(buttons[1],4);b.tick(1);assert.ok(Number(b.el('ability-bar').children[1].querySelector('.cooldown').textContent)>0);b.el('move-stick').emit('pointerup',{pointerId:1});b.el('aim-stick').emit('pointerup',{pointerId:2});assert.notEqual(JSON.stringify(b.debug().match),state);
 const savedStanceLeft=buttons[4].style.left;b.tick(320);b.click('view-results');b.click('play-again');b.tick(3);assert.equal(b.el('ability-bar').children[4].style.left,savedStanceLeft);b.click('pause-menu');const stopped=JSON.stringify(b.debug().match);b.tick(20);assert.equal(JSON.stringify(b.debug().match),stopped);b.click('play');b.click('confirm-summoner');b.tick(3);assert.equal(b.el('move-control').style.position,'fixed');assert.deepEqual(b.errors,[]);
 const again=boot(844,390,store);again.click('play');again.click('confirm-summoner');again.tick(3);assert.equal(again.el('ability-bar').children[0].style.transform,'scale(1.2)');assert.equal(again.el('move-control').style.left,b.el('move-control').style.left);
});
test('confirmed Reset restores exact default layout and Cancel never partially saves',()=>{
 const store=storage(),b=boot(844,390,store);customize(b);const original=store.getItem(LAYOUT_CONFIG.key);b.click('edit-controls');b.tick(2);b.click('layout-reset');assert.equal(store.getItem(LAYOUT_CONFIG.key),original);assert.equal(b.el('layout-reset').textContent,'CONFIRM RESET');b.click('layout-reset');b.click('layout-cancel');assert.equal(store.getItem(LAYOUT_CONFIG.key),original);b.click('edit-controls');b.tick(2);b.click('layout-reset');b.click('layout-reset');b.click('layout-save');assert.deepEqual(JSON.parse(store.getItem(LAYOUT_CONFIG.key)),defaultLayout());launch(b);for(const el of [b.el('move-control'),b.el('aim-control'),...b.el('ability-bar').children])assert.ok(!el.style.position);assert.equal(b.document.body.flags.has('custom-controls'),false);
});
test('failed Save keeps editor open and saved preferences intact',()=>{
 const b=boot(844,390,{getItem:()=>null,setItem(){throw Error('Quota');}});editor(b);change(b,'x',.2);b.click('layout-save');assert.equal(b.debug().ux,'control-editor');assert.match(b.el('layout-status').textContent,/not saved/);b.click('layout-cancel');assert.equal(b.debug().ux,'settings');
});
test('normalized layouts remain inside safe areas at small, standard and wide sizes; touch bounds scale with appearance',()=>{
 for(const [w,h]of [[568,320],[844,390],[932,430]])for(const [x,y]of [[0,0],[1,1],[.25,.7]]){const area={left:20,top:12,width:w-40,height:h-24};const b=layoutBounds({x,y,scale:1.35},104,area);assert.ok(b.left>=area.left&&b.top>=area.top);assert.ok(b.left+b.width<=area.left+area.width+.001);assert.ok(b.top+b.height<=area.top+area.height+.001);}
 const store=storage();store.setItem(LAYOUT_CONFIG.key,JSON.stringify({version:1,controls:{move:{x:.15,y:.7,scale:1.2,opacity:.65},basic:{x:.5,y:.8,scale:1.2,opacity:.8}}}));for(const [w,h]of [[568,320],[844,390],[932,430]]){const b=boot(w,h,store);b.click('play');b.click('confirm-summoner');b.tick(185);const r=b.el('move-stick').getBoundingClientRect();assert.ok(r.left>=12&&r.top>=12);assert.ok(r.left+r.width<=w-12);b.el('move-stick').emit('pointerdown',{pointerId:1,clientX:r.left+r.width,clientY:r.top+r.height/2});assert.ok(b.debug().input.moveX>.9);assert.equal(b.el('ability-bar').children[0].getBoundingClientRect().width,66*1.2);assert.deepEqual(b.errors,[]);}
});
test('a buried control cannot be saved and the selector can recover it; limits keep controls usable',()=>{
 const b=boot(844,390,storage());editor(b);select(b,'move');change(b,'x',.3);change(b,'y',.7);select(b,'aim');change(b,'x',.3);change(b,'y',.7);assert.equal(b.el('layout-save').disabled,true);assert.match(b.el('layout-overlap').textContent,/fully covered/);select(b,'aim');change(b,'x',.8);assert.equal(b.el('layout-save').disabled,false);change(b,'scale',0);assert.equal(Number(b.el('layout-scale').value),LAYOUT_CONFIG.minScale);change(b,'opacity',0);assert.equal(Number(b.el('layout-opacity').value),LAYOUT_CONFIG.minOpacity);b.click('layout-save');assert.equal(b.debug().ux,'settings');
});
test('customized slots still activate Basic, both skills and ready Ultimate for Kit, Set and both Riven stances',()=>{
 for(const id of ['kit-asher','set','riven']){const b=boot(844,390,storage());customize(b);b.click('practice');b.el('summoner').value=id;b.el('summoner').onchange();b.click('start');b.tick(2);
  const basic=b.el('ability-bar').children[0],r=basic.getBoundingClientRect();basic.emit('pointerdown',{pointerId:10,clientX:r.left+r.width/2,clientY:r.top+r.height/2});b.tick(2);if(id==='riven'){assert.equal(Number(basic.querySelector('.cooldown').textContent),0);basic.emit('pointerup',{pointerId:10});b.tick(2);}assert.ok(Number(basic.querySelector('.cooldown').textContent)>0,id+' Basic');basic.emit('pointerup',{pointerId:10});
  for(const [slot,frames]of [[1,2],[2,35],[3,2]]){const button=b.el('ability-bar').children[slot];press(button,20+slot);b.tick(frames);assert.ok(Number(b.el('ability-bar').children[slot].querySelector('.cooldown').textContent)>0,id+' slot '+slot);b.tick(40);}
  if(id==='riven'){press(b.el('ability-bar').children[4],40);b.tick(2);assert.equal(b.debug().combat.stance,'pulse');assert.ok(b.el('ability-bar').children[4].style.left);b.tick(380);for(const slot of [1,2]){press(b.el('ability-bar').children[slot],50+slot);b.tick(2);assert.ok(Number(b.el('ability-bar').children[slot].querySelector('.cooldown').textContent)>0);}}
  assert.deepEqual(b.errors,[]);
 }
});