import test from 'node:test';import assert from 'node:assert/strict';
import {CrownfallMatch} from '../src/match.js';import {CrownfallRules} from '../src/crownfall-rules.js';import {CrownfallBot} from '../src/match-bots.js';
const idle={moveX:0,moveZ:0};
const advance=(m,s)=>{for(let i=0;i<Math.ceil(s*60);i++)m.step(idle);};
function setup(name='kit-asher',settings={}){const m=new CrownfallMatch(name,{countdownSeconds:0,...settings});for(const a of m.actors)a.bot={read:()=>idle};m.start();return m;}
test('prematch/countdown lock all six actors, direct cast/damage, timer, control and CP',()=>{const m=new CrownfallMatch();const before=m.snapshot();m.step({moveX:1,actions:[{id:'dragon'}]});assert.equal(m.phase,'prematch');m.start();assert.equal(m.phase,'countdown');for(const a of m.actors){const hp=a.sim.player.health;a.sim.damage(a.sim.player,999);assert.equal(a.sim.player.health,hp);assert.equal(a.sim.cast(a.sim.activeAbilities()[0].id),false);}advance(m,3);assert.equal(m.phase,'active');assert.equal(m.rules.elapsed,0);assert.equal(m.rules.control,.5);assert.deepEqual(m.rules.cp,{1:0,2:0});assert.deepEqual(m.entities.map(p=>[p.x,p.z]),before.actors.map(p=>[p.x,p.z]));m.step(idle);assert.ok(m.rules.elapsed>0);});
test('all Ultimates start locked; actual mitigated damage charges both teams, no overkill credit',()=>{for(const name of ['kit-asher','set','riven']){const m=setup(name),s=m.human,ult=s.activeAbilities().find(a=>a.ultimate),enemy=m.entities[3];assert.equal(s.player.ultimateMeter,0);assert.equal(s.cast(ult.id),false);s.damage(enemy,100,s.player);const dealt=enemy.maxHealth-enemy.health;assert.ok(Math.abs(s.player.ultimateMeter-dealt*.04)<1e-9);assert.ok(Math.abs(enemy.ultimateMeter-dealt*.025)<1e-9);s.damage(enemy,99999,s.player);assert.ok(s.player.ultimateMeter<=enemy.maxHealth*.04+1e-8);}});
test('movement, waiting, territorial scoring, misses and friendly damage do not charge Ultimate',()=>{const m=setup(),s=m.human;s.player.x=3;m.entities.filter(p=>p.team===2).forEach(p=>{p.x=10;});s.cast('whip',Math.PI);advance(m,4);assert.ok(m.rules.cp[1]>0);assert.equal(s.player.ultimateMeter,0);s.damage(m.entities[1],10,s.player);assert.equal(s.player.ultimateMeter,0);s.step({moveX:1,moveZ:0});assert.equal(s.player.ultimateMeter,0);});
test('100% permits each Ultimate, consumes charge, preserves cooldown, rejects rapid duplicates',()=>{for(const name of ['kit-asher','set','riven']){const m=setup(name),s=m.human,a=s.activeAbilities().find(a=>a.ultimate);s.player.ultimateMeter=100;assert.equal(s.cast(a.id,0),true);assert.equal(s.player.ultimateMeter,0);for(let i=0;i<20;i++)assert.equal(s.cast(a.id,0),false);assert.equal(s.cooldowns.remaining(a.id,s.now),a.cooldown);s.player.ultimateMeter=100;assert.equal(s.cast(a.id),false);}});
test('bots omit Ultimate actions until charged and normal combat produces charge',()=>{const m=setup();const s=m.actors[3].sim,p=s.player;p.x=0;m.human.player.x=2;let bot=new CrownfallBot(0);assert.ok(bot.read(s,m).actions.every(a=>!s.ability(a.id)?.ultimate));p.ultimateMeter=100;bot=new CrownfallBot(0);assert.ok(bot.read(s,m).actions.some(a=>s.ability(a.id)?.ultimate));});
test('normal ability spam produces one accepted cast per cooldown, including stance shared channels',()=>{for(const name of ['kit-asher','set','riven']){const m=setup(name),s=m.human;for(const a of s.activeAbilities().filter(a=>!a.ultimate)){let accepted=0;for(let i=0;i<20;i++)if(s.cast(a.id,0))accepted++;assert.ok(accepted<=1,a.id);}}const m=setup('riven'),s=m.human;s.cast('elf-dance');s.cast('amp');s.cast('stance');assert.equal(s.cast('percussive-solo'),false);assert.equal(s.cast('amp'),false);assert.equal(s.stance,'pulse');});
test('respawn protection blocks damage, CC hit eligibility, charge and deaths, then expires',()=>{const m=setup('riven',{respawnSeconds:1,protectionSeconds:2}),s=m.human,enemy=m.actors[3].sim;enemy.damage(s.player,99999,enemy.player);advance(m,1.1);assert.equal(s.player.dead,false);assert.ok(m.protected(s.player));const hp=s.player.health,meter=enemy.player.ultimateMeter,tickets=m.rules.tickets[1];enemy.damage(s.player,99999,enemy.player);assert.equal(s.player.health,hp);assert.equal(enemy.player.ultimateMeter,meter);assert.equal(m.rules.tickets[1],tickets);assert.equal(enemy.valid(s.player),false);advance(m,2.1);assert.equal(m.protected(s.player),false);enemy.damage(s.player,10,enemy.player);assert.ok(s.player.health<hp);});
test('offensive action ends protection on success; rejected cast/buff/stance do not',()=>{const m=setup('riven'),s=m.human;s.player.protectedUntil=10;s.cast('amp');s.cast('stance');assert.ok(m.protected(s.player));assert.equal(s.cast('death-scream'),false);assert.ok(m.protected(s.player));assert.equal(s.cast('pulse',0),true);assert.equal(m.protected(s.player),false);});
test('dead and reserved respawns cannot contribute; results prevent recalculation',()=>{const r=new CrownfallRules(),e=[{team:1,x:20,z:0,dead:true},{team:2,x:-4,z:0,dead:false}];assert.ok(r.measure(e)<.5);e[0].dead=false;e[0].respawnReserved=true;assert.ok(r.measure(e)<.5);delete e[0].respawnReserved;e[0].x=-8;assert.ok(r.measure(e)<(-4+21)/42);r.finish(1,'points');const c=r.control;e[0].x=-21;r.measure(e);assert.equal(r.control,c);});
test('regulation resolves CP first, then territory, then exact draw',()=>{for(const scenario of [{cp:[20,10],x:-4,w:1},{cp:[10,20],x:4,w:2},{cp:[10,10],x:4,w:1},{cp:[10,10],x:-4,w:2},{cp:[10,10],x:0,w:0}]){const r=new CrownfallRules({timeLimitSeconds:1,graceSeconds:10});r.cp={1:scenario.cp[0],2:scenario.cp[1]};r.step([{team:1,x:scenario.x-1,z:0},{team:2,x:scenario.x+1,z:0}],1);assert.equal(r.result.winner,scenario.w);assert.equal(r.result.reason,'regulation');}});
test('complete 3v3 lifecycle fights, scores, concludes, blocks mutations and fresh rematch resets everything',()=>{const settings={countdownSeconds:1,timeLimitSeconds:60,startingTickets:9};const m=new CrownfallMatch('riven',settings),bot=new CrownfallBot(0);m.start();let charge=false,death=false,cp=false,moved=false;for(let i=0;i<62*60&&!m.rules.result;i++){m.step(bot.read(m.human,m));charge ||=m.entities.some(p=>p.ultimateMeter>0);death ||=m.entities.some(p=>p.dead);cp ||=m.rules.cp[1]+m.rules.cp[2]>0;moved ||=m.rules.control!==.5;}assert.ok(m.rules.result);assert.ok(charge&&death&&cp&&moved);const frozen=JSON.stringify(m.snapshot());for(const a of m.actors){a.sim.cast(a.sim.activeAbilities()[0].id);a.sim.damage(m.entities[0],99999,a.sim.player);a.sim.step({moveX:1,moveZ:0});}m.step(idle);assert.equal(JSON.stringify(m.snapshot()),frozen);const fresh=new CrownfallMatch('riven',settings);assert.equal(fresh.phase,'prematch');assert.equal(fresh.rules.elapsed,0);assert.equal(fresh.rules.control,.5);assert.deepEqual(fresh.rules.cp,{1:0,2:0});assert.deepEqual(fresh.rules.tickets,{1:9,2:9});for(const a of fresh.actors){const p=a.sim.player;assert.equal(p.health,p.maxHealth);assert.equal(p.dead,false);assert.equal(p.respawnAt,0);assert.equal(p.ultimateMeter,0);assert.equal(p.x,p.spawn.x);assert.deepEqual(a.sim.cooldowns.ends,{});assert.equal(a.sim.stance,a.sim.definition.initialStance||null);assert.equal(a.bot?.nextThink||0,0);}fresh.start();assert.equal(fresh.phase,'countdown');});