import {withoutM92Presentation} from './helpers/m92-presentation-seams.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {withoutM86Art} from './helpers/m86-render-seams.js';
import {boot} from './helpers/game-browser.js';
import {UX_SUMMONERS} from '../src/game-ux.js';
function launch(b,id='kit-asher'){
 b.click('play');const index=UX_SUMMONERS.findIndex(s=>s.id===id);b.el('summoner-cards').children[index].onclick();b.click('confirm-summoner');assert.equal(b.debug().ux,'match-loading');b.tick(1);assert.equal(b.debug().ux,'match-loading');b.tick(1);assert.equal(b.debug().ux,'countdown');
}
const settle=b=>{b.tick(183);assert.equal(b.debug().ux,'active');};
function assertFresh(b,id){const d=b.debug();assert.equal(d.combat.summoner,id);assert.equal(d.match.phase,'countdown');assert.equal(d.match.control,.5);assert.deepEqual(d.match.cp,{'1':0,'2':0});assert.deepEqual(d.match.tickets,{'1':15,'2':15});assert.equal(d.match.elapsed,0);assert.equal(d.match.result,null);assert.equal(d.match.rotations,0);assert.equal(d.match.rewards,0);assert.ok(d.match.camps.every(c=>!c.dead&&c.health>0));assert.ok(d.match.actors.every(p=>!p.dead&&!p.eliminated&&p.finalRespawnAvailable&&p.ultimateMeter===0&&p.kills===0&&p.deaths===0&&p.assists===0&&p.damage===0&&p.pressureSeconds===0));assert.deepEqual(d.combat.modifiers,{});assert.equal(d.combat.temporary.length,0);assert.equal(d.combat.leaping,false);assert.equal(d.combat.sequencing,false);if(id==='riven'){assert.equal(d.combat.stance,'reso');assert.ok(d.combat.scythes.every(s=>s.phase==='orbit'));}}
test('main menu uses only approved artwork; M7 gameplay, arena and HUD files remain unchanged',()=>{
 for(const file of ['config','simulation','combat-data','riven-data','summoners','combat-core','combat','modifiers','advanced-actions','returning-weapons','match-data','crownfall-rules','match-bots','wilderness','match','camera','input','ability-input','renderer','combat-view','combat-feedback','match-ui','ui','hud-presentation'])assert.equal((file==='renderer'?withoutM86Art:s=>withoutM92Presentation(s,file))(fs.readFileSync(new URL('../src/'+file+'.js',import.meta.url),'utf8')),execFileSync('git',['show','e9e3824:src/'+file+'.js'],{encoding:'utf8'}),file);
 const expected='d785263520bd9ecef5b0c680550e322c8eb39a0d18ea15d055b77d316a697259';for(const path of ['assets/ucl-arena-menu.jpeg','dist/assets/ucl-arena-menu.jpeg'])assert.equal(createHash('sha256').update(fs.readFileSync(new URL('../'+path,import.meta.url))).digest('hex'),expected);
 const b=boot();assert.deepEqual(b.errors,[]);assert.equal(b.debug().ux,'main-menu');const before=b.debug();b.tick(180);assert.deepEqual(b.debug(),before);assert.equal(b.uploads,0);assert.equal(b.el('game-layer').inert,true);assert.equal(b.el('main-menu').hidden,false);
});
test('PLAY selects each authoritative Summoner and exposes selected role/class before confirmation',()=>{
 const b=boot();b.click('play');assert.equal(b.debug().ux,'summoner-select');const cards=b.el('summoner-cards').children;assert.equal(cards.length,3);
 for(const [i,s]of UX_SUMMONERS.entries()){cards[i].onclick();assert.equal(b.el('selection-name').textContent,s.name);assert.equal(b.debug().combat.summoner,s.id);assert.equal(cards[i].attrs['aria-pressed'],'true');assert.equal(cards.filter(c=>c.attrs['aria-pressed']==='true').length,1);assert.match(cards[i].innerHTML,new RegExp(s.role));assert.match(cards[i].innerHTML,new RegExp(s.aether));}
 assert.equal(UX_SUMMONERS[2].aether,'Shaper');b.click('selection-back');assert.equal(b.debug().ux,'main-menu');
});
test('menu and select touches/keyboard cannot queue hidden movement or abilities; countdown stays gated',()=>{
 const b=boot();for(const screen of ['main-menu','summoner-select']){if(screen==='summoner-select')b.click('play');const d=b.debug();b.window.emit('keydown',{code:'KeyW'});b.window.emit('keydown',{code:'KeyQ'});b.window.emit('keydown',{code:'Space'});b.el('move-stick').emit('pointerdown',{pointerId:1,clientX:100,clientY:50});b.el('ability-bar').children[1].emit('pointerdown',{pointerId:2,clientX:50,clientY:50});b.el('ability-bar').children[1].emit('pointerup',{pointerId:2});b.tick(5);assert.equal(b.debug().tick,d.tick);assert.equal(b.debug().input.moveX,0);assert.equal(b.debug().input.moveZ,0);}
 b.click('confirm-summoner');b.tick(2);assertFresh(b,'kit-asher');const p=b.debug().player;b.tick(90);assert.equal(b.debug().match.elapsed,0);assert.equal(b.debug().match.control,.5);assert.equal(b.debug().player.x,p.x);assert.equal(b.debug().player.z,p.z);b.tick(93);assert.equal(b.debug().ux,'active');assert.equal(b.debug().input.moveZ,0);
});
test('complete match → victory → results → rematch → menu → new match has no state leakage',()=>{
 const b=boot();b.el('setting-timeLimitSeconds').value='5';launch(b,'riven');assertFresh(b,'riven');settle(b);
 b.window.emit('keydown',{code:'KeyF'});b.tick(1);assert.equal(b.debug().combat.stance,'pulse');b.window.emit('keydown',{code:'KeyW'});b.window.emit('keydown',{code:'Space'});b.tick(310);assert.equal(b.debug().ux,'victory');assert.ok(b.debug().match.result);assert.equal(b.el('results').hidden,true);assert.equal(b.debug().paused,true);
 const ended=JSON.stringify(b.debug().match);b.tick(12);assert.equal(JSON.stringify(b.debug().match),ended);assert.equal(b.debug().input.moveZ,0);b.click('view-results');assert.equal(b.debug().ux,'results');assert.equal(b.el('results').hidden,false);assert.equal(b.el('result-rows').children.length,6);assert.match(b.el('results-player').textContent,/Pressure/);assert.ok(b.el('results-team').textContent);b.tick(30);assert.equal(JSON.stringify(b.debug().match),ended);
 b.click('play-again');b.tick(2);assertFresh(b,'riven');settle(b);b.tick(305);assert.equal(b.debug().ux,'victory');b.tick(121);assert.equal(b.debug().ux,'results');b.click('back-menu');assert.equal(b.debug().ux,'main-menu');const menu=JSON.stringify(b.debug().match);b.tick(300);assert.equal(JSON.stringify(b.debug().match),menu);launch(b,'set');assertFresh(b,'set');settle(b);assert.deepEqual(b.errors,[]);
});
test('pause/resume, settings and existing practice remain functional without changing gameplay clocks',()=>{
 const b=boot();b.click('open-settings');assert.equal(b.debug().ux,'settings');b.el('quality').onchange({target:{value:'low'}});assert.equal(b.debug().quality,'low');b.click('settings-back');launch(b);settle(b);b.click('pause');b.tick(1);assert.equal(b.debug().ux,'paused');const paused=JSON.stringify(b.debug().match);b.tick(120);assert.equal(JSON.stringify(b.debug().match),paused);b.click('start');b.tick(3);assert.equal(b.debug().ux,'active');b.click('pause-menu');assert.equal(b.debug().ux,'main-menu');b.click('open-settings');b.click('practice');assert.equal(b.debug().mode,'training');b.click('start');b.tick(5);assert.equal(b.debug().ux,'training');b.click('pause-menu');b.click('play');assert.equal(b.debug().mode,'match');assert.equal(b.debug().ux,'summoner-select');assert.deepEqual(b.errors,[]);
});
test('responsive screen structure supports compact and wide mobile frames with unique IDs and safe edges',()=>{
 const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../style.css',import.meta.url),'utf8');const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);assert.match(css,/center 42%\/cover/);assert.match(css,/safe-area-inset-left/);assert.match(css,/max-height:365px/);assert.match(css,/min-height:44px/);
 for(const [w,h]of [[568,320],[667,375],[844,390],[932,430]]){const b=boot(w,h);launch(b,'set');b.tick(4);assert.equal(b.debug().ux,'countdown');assert.deepEqual(b.errors,[]);}
});