import {KIT} from './combat-data.js';
import {CONFIG} from './config.js';
export class AbilityInput {
 constructor(input,getFacing,definition=KIT){this.definition=definition;this.input=input;this.getFacing=getFacing;this.actions=[];this.attackHeld=false;this.active=null;this.preview=null;this.buttons=new Map();
  this.setDefinition(definition);
  window.addEventListener('keydown',e=>{if(!this.input.enabled||e.repeat||/SELECT|INPUT|BUTTON/.test(e.target?.tagName||''))return;const a=[...this.definition.abilities,...(this.definition.bonus?[this.definition.bonus]:[])].find(a=>a.key===e.code);if(!a)return;e.preventDefault();if(this.releaseBasic(a)){this.pendingBasic=null;this.keyboardBasic={ability:a,angle:this.getFacing(),started:e.timeStamp};this.preview={ability:a,angle:this.keyboardBasic.angle,cancel:false};}else if(a.basic)this.attackHeld=true;else this.actions.push({id:a.id,angle:this.getFacing()});});
  window.addEventListener('keyup',e=>{if(e.code==='Space'){if(this.keyboardBasic){const p=this.keyboardBasic;this.commitBasic(p.ability,e.timeStamp-p.started<180?p.angle:this.preview.angle);this.keyboardBasic=null;this.preview=null;}this.attackHeld=false;}});
  for(const event of ['blur','resize'])window.addEventListener(event,()=>this.clear());document.addEventListener('visibilitychange',()=>this.clear());
 }
 setDefinition(definition){
  this.clear();this.layoutKey=definition.id+definition.abilities.map(a=>a.id).join('|');this.definition=definition;this.buttons.clear();const bar=document.getElementById('ability-bar');bar.innerHTML='';
  for(const [index,a] of [...this.definition.abilities,...(this.definition.bonus?[this.definition.bonus]:[])].entries()){
   const button=document.createElement('button');button.className='ability ability-'+a.id;button.dataset.slot=index;button.setAttribute('aria-label',a.name);button.innerHTML=`<strong>${(['〰','➤','◎','♜','✦'][index]||'✦')}</strong><span>${a.short}</span><b class="cooldown"></b>`;bar.append(button);this.buttons.set(a.id,button);
   button.addEventListener('pointerdown',e=>{if(!this.input.enabled||this.active)return;e.preventDefault();button.setPointerCapture(e.pointerId);this.active={id:a.id,pointer:e.pointerId,button,x:e.clientX,y:e.clientY,angle:this.getFacing(),started:e.timeStamp,cancel:false,dragged:false};if(a.aim==='ground')this.active.targetOffset={x:Math.sin(this.active.angle)*a.range*.65,z:Math.cos(this.active.angle)*a.range*.65};this.preview={ability:a,angle:this.active.angle,cancel:false,targetOffset:this.active.targetOffset};if(this.releaseBasic(a))this.pendingBasic=null;else if(a.basic)this.attackHeld=true;});
   button.addEventListener('pointermove',e=>{const p=this.active;if(!p||p.pointer!==e.pointerId)return;const dx=e.clientX-p.x,dz=e.clientY-p.y,d=Math.hypot(dx,dz);p.cancel=d>150;if(d>12){p.dragged=true;p.angle=Math.atan2(dx,dz/CONFIG.camera.tiltSin);}if(a.aim==='ground'&&p.dragged){const x=dx/90*a.range,z=dz/(90*CONFIG.camera.tiltSin)*a.range,l=Math.hypot(x,z),f=l>a.range?a.range/l:1;p.targetOffset={x:x*f,z:z*f};}this.preview={ability:a,angle:p.angle,cancel:p.cancel,targetOffset:p.targetOffset};if(a.basic&&!this.releaseBasic(a))this.attackHeld=!p.cancel;});
   button.addEventListener('pointerup',e=>{const p=this.active;if(!p||p.pointer!==e.pointerId)return;if(!p.cancel&&this.releaseBasic(a))this.commitBasic(a,!p.dragged&&e.timeStamp-p.started<180?p.angle:this.preview.angle);else if(!p.cancel&&!this.definition.abilities.find(a=>a.id===p.id)?.basic)this.actions.push({id:p.id,angle:p.angle,...(p.targetOffset?{targetOffset:{...p.targetOffset}}:{})});this.release();});
   for(const name of ['pointercancel','lostpointercapture'])button.addEventListener(name,e=>{if(this.active?.pointer===e.pointerId)this.release();});
  }
 }
 release(){const p=this.active;this.active=null;this.preview=null;this.attackHeld=false;if(p&&p.button.hasPointerCapture(p.pointer))p.button.releasePointerCapture(p.pointer);}
 clear(){this.release();this.actions=[];this.keyboardBasic=null;this.pendingBasic=null;}
 releaseBasic(a){return this.definition.id==='riven'&&a.basic;}
 commitBasic(a,angle){this.actions.push({id:a.id,angle});this.pendingBasic=a.effect==='weaponSequence'&&this.sim?.weapons.next===0?{id:a.id,angle,submitted:false}:null;}
 read(){const actions=this.actions.splice(0);if(this.pendingBasic&&actions.some(a=>a.id===this.pendingBasic.id))this.pendingBasic.submitted=true;return {actions,attackHeld:this.attackHeld};}
 update(sim){this.sim=sim;const pending=this.pendingBasic;if(pending?.submitted){if(!this.input.enabled||sim.player.dead||sim.stance!=='reso'||sim.weapons.next!==1||sim.weapons.returning)this.pendingBasic=null;else if(sim.cooldowns.ready(sim.ability(pending.id).cooldownKey||pending.id,sim.now)){this.actions.push({id:pending.id,angle:pending.angle});this.pendingBasic=null;}}const active=sim.activeAbilities();if(this.layoutKey!==sim.definition.id+active.map(a=>a.id).join('|'))this.setDefinition({...sim.definition,abilities:active});for(const [id,button] of this.buttons){const a=sim.ability(id),remaining=sim.cooldowns.remaining(a.cooldownKey||id,sim.now),bonus=id===sim.definition.bonus?.id;button.hidden=bonus&&!sim.temporary.available(id,sim.now);if(button.hidden&&this.active?.id===id)this.release();const meterLocked=!!sim.match&&a.ultimate&&!sim.match.ultimateReady(sim);button.classList.toggle('unready',remaining>0||sim.player.dead||meterLocked||!!sim.match&&!sim.match.active);button.style.setProperty('--cool',`${remaining/a.cooldown*100||0}%`);button.querySelector('.cooldown').textContent=remaining>0?remaining.toFixed(1):meterLocked?Math.floor(sim.player.ultimateMeter)+'%':bonus?Math.ceil((sim.temporary.grants.get(id)?.expires||sim.now)-sim.now)+'s':'';}}
}