import {TRAINING} from './combat-data.js';
import {hasStatus} from './combat-core.js';
export function drawCombat(mesh,sim,preview,visuals=null){const m=mesh;
 if(sim.feedback&&(!sim.match||sim===sim.match.human))sim.feedback.drawWorld(m);
 if(!sim.match||sim===sim.match.human)for(const zone of sim.training.zones){m.box(zone.x,.07,zone.z,zone.w,.005,zone.d,'#29493b');for(const z of [zone.z-zone.d/2,zone.z+zone.d/2])m.box(zone.x,.08,z,zone.w,.02,.07,'#7caf69');for(const x of [zone.x-zone.w/2,zone.x+zone.w/2])m.box(x,.08,zone.z,.07,.02,zone.d,'#7caf69');}
 if(!sim.match)for(const t of sim.targets){if(t.dead){m.ring(t.x,.12,t.z,.6,.04,'#596369');continue;}const stunned=hasStatus(t,'stun',sim.now),color=stunned?'#edc85e':t.team===sim.player.team?'#5bbaa3':t.kind==='summoner'?'#8573ab':'#677b8b';m.disc(t.x,.12,t.z,.6,'#262637');m.ring(t.x,.13,t.z,.65,.06,color);m.box(t.x,.15,t.z,.65,1.05,.48,color);m.box(t.x,1.2,t.z,.43,.4,.4,'#b5afb7');m.box(t.x-.45,.7,t.z,.2,.7,.25,color);m.box(t.x+.45,.7,t.z,.2,.7,.25,color);if(stunned)m.ring(t.x,1.9,t.z,.48,.08,'#ffe179');}
 if(sim.match&&sim===sim.match.human)for(const c of sim.match.wilderness.camps){const color=c.dead?'#55605d':c.type==='mobility'?'#77d7df':c.type==='cooldown'?'#b5a3ee':c.type==='defense'?'#8cc49b':'#e6ba72';m.ring(c.home.x,.12,c.home.z,c.major?2:1.2,.08,color);if(c.dead)continue;m.box(c.x,.2,c.z,c.major?2.2:1, c.major?1.8:1,c.major?1.7:.8,color);m.box(c.x,.9,c.z+.3,c.major?1.6:.8,c.major?.8:.4,c.major?1:.6,'#4b5961');for(const side of [-1,1])m.box(c.x+side*(c.major?.9:.4),c.major?2:1.2,c.z,.2,.4,.25,color);}
 const sector=(x,z,angle,range,arc,col,edge='#ffc364')=>{const n=32;for(let i=0;i<n;i++){const a=angle-arc/2+arc*i/n,b=angle-arc/2+arc*(i+1)/n;m.tri([x,.18,z],[x+Math.sin(a)*range,.18,z+Math.cos(a)*range],[x+Math.sin(b)*range,.18,z+Math.cos(b)*range],col);}
  for(let i=0;i<n;i++){const a=angle-arc/2+arc*i/n,b=angle-arc/2+arc*(i+1)/n;m.quad([x+Math.sin(a)*range,.2,z+Math.cos(a)*range],[x+Math.sin(b)*range,.2,z+Math.cos(b)*range],[x+Math.sin(b)*(range-.12),.2,z+Math.cos(b)*(range-.12)],[x+Math.sin(a)*(range-.12),.2,z+Math.cos(a)*(range-.12)],edge);}};
 for(const e of sim.effects.items){if(!e.active||visuals?.replacesEffect(sim,e.type))continue;if(e.type==='pulseAOE'||e.type==='scream'){m.ring(e.x,.22,e.z,e.range,.18,e.type==='scream'?'#e6fff8':'#77cfbf');m.ring(e.x,.65,e.z,e.range*.75,.1,'#91e9d3');}if(e.type==='melee')sector(e.x,e.z,e.angle,e.range,e.arc,e.combo===2?'#8951b5':'#50376f','#d2adf4');if(e.type==='pantherTrail'||e.type==='buffPulse')m.ring(e.x,.17,e.z,e.range,.1,'#b27ae0');if(e.type==='slam'){m.disc(e.x,.17,e.z,e.range,'#503864');m.ring(e.x,.22,e.z,e.range,.2,'#d7afff');for(let i=0;i<8;i++){const angle=i*Math.PI/4;m.box(e.x+Math.sin(angle)*e.range*.7,.2,e.z+Math.cos(angle)*e.range*.7,.15,.55,.15,'#be90ef');}}if(e.type==='cone')sector(e.x,e.z,e.angle,e.range,e.arc,e.combo?'#bd6030':'#975132');if(e.type==='radial'){m.disc(e.x,.16,e.z,e.range,'#974731');m.ring(e.x,.21,e.z,e.range,.18,'#ffb84c');m.ring(e.x,.6,e.z,e.range*.85,.11,'#ef842e');}if(e.type==='trail')m.disc(e.x,.15,e.z,e.range,'#be632d',8);}
 for(const s of sim.projectiles.items){if(!s.active)continue;const fx=Math.sin(s.angle),fz=Math.cos(s.angle),a=s.ability;if(visuals?.replacesEffect(sim,s.type)){/* Authored projectile uses the same live position; keep its hit-path ring below. */}else if(s.type==='dragon'){
  for(let i=0;i<6;i++){const x=s.x-fx*i*.42,z=s.z-fz*i*.42;m.box(x,.35,z,(1-i*.11)*1.7,.8-i*.09,.65,i%2?'#ffbd4c':'#e8752b',s.angle);}
  m.box(s.x,.65,s.z,1.3,.6,1.15,'#ffc764',s.angle);m.box(s.x+fx*.6,.6,s.z+fz*.6,.9,.36,.8,'#ef9335',s.angle);
  for(const side of [-1,1]){m.box(s.x+fz*side*.48,1.2,s.z-fx*side*.48,.17,.5,.27,'#ffe8a5',s.angle);m.tri([s.x,.8,s.z],[s.x+fz*side*2.1-fx*1,.4,s.z-fx*side*2.1-fz*1],[s.x-fx*1.7,.7,s.z-fz*1.7],'#e68836');}
 }else if(s.type==='blast'){m.box(s.x-fx,.65,s.z-fz,a.width*1.6,.65,3.5,'#ffe7a7',s.angle);m.box(s.x-fx*2,.55,s.z-fz*2,a.width*2,.8,1.8,'#ef8634',s.angle);}else if(s.type==='reso-scythe'||a.visual==='scythe'){if(s.phase==='orbit'&&sim.stance!=='reso')continue;const spin=sim.now*9;m.box(s.x,.72,s.z,.08,.08,1.05,'#c4fff0',spin);m.box(s.x+Math.sin(spin)*.38,.72,s.z+Math.cos(spin)*.38,.62,.12,.16,'#84e5d0',spin);m.box(s.x+Math.cos(spin)*.25+Math.sin(spin)*.28,.72,s.z-Math.sin(spin)*.25+Math.cos(spin)*.28,.12,.12,.35,'#b8fff0',spin);}else if(a.visual==='wave'){m.box(s.x,.55,s.z,1.5,.5,.17,'#9ef9e7',s.angle);m.ring(s.x,.2,s.z,.7,.09,'#72b9af');}else m.disc(s.x,.6,s.z,.24,'#d6a9ff',10);
 m.ring(s.x,.16,s.z,a.width,.045,s.team===1?'#8ae0cc':'#ed94aa',20);
 }
 if(sim.match)for(const t of [sim.player])if(!t.dead&&sim.match.protected(t)){m.ring(t.x,.2,t.z,.95,.12,'#b3f2ff');m.ring(t.x,1.35,t.z,.65,.07,'#efffff');}
 for(const zone of sim.zones)m.ring(zone.source.x,.2,zone.source.z,zone.ability.range,.07,'#73cbbb');
 if(sim.player.modifiers?.amp?.expires>sim.now&&!sim.player.dead){m.ring(sim.player.x,.2,sim.player.z,1,.1,'#c4fff0');m.ring(sim.player.x,1.2,sim.player.z,.65,.06,'#83e4cb');}
 if(sim.definition.passive.effect==='alliedAura'&&!sim.player.dead){m.ring(sim.player.x,.14,sim.player.z,sim.definition.passive.radius,.035,sim.auraAllies.length?'#76d8ba':'#485e63');for(const t of [sim.player,...sim.auraAllies])if(t.modifiers?.['aura:'+sim.player.id])m.ring(t.x,.18,t.z,.85,.08,'#76d8ba');}
 if(sim.player.modifiers?.warcry?.expires>sim.now&&!sim.player.dead){m.ring(sim.player.x,.19,sim.player.z,1.1,.12,'#cc9aff');m.ring(sim.player.x,1.3,sim.player.z,.6,.055,'#bd84ff');}
 for(const impact of sim.advanced.impacts){const progress=Math.max(0,Math.min(1,(sim.now-impact.created)/impact.ability.castTime)),height=.4+Math.pow(1-progress,.6)*5;m.ring(impact.x,.2,impact.z,impact.ability.radius,.08,sim.player.team===1?'#83d9c9':'#ed94aa');m.disc(impact.x,.15,impact.z,.5,'#9871aa');if(visuals?.replacesEffect(sim,'fallingClaw'))continue;m.box(impact.x,height,impact.z,1.8,1.25,1.5,'#9f6ec8');for(let i=0;i<4;i++)m.box(impact.x-.7+i*.46,height,impact.z+.75,.42,.7,.5,'#ceb0ec');m.box(impact.x+1,height+.2,impact.z,.5,.8,.65,'#b38bdb');}
 if(preview&&!sim.player.dead){const {ability:a,angle,cancel}=preview,p=sim.player,col=cancel?'#9a4352':'#db9e55';if(a.aim==='self'){m.ring(p.x,.22,p.z,1.2,.07,'#b588ed');}else if(a.aim==='ground'){const o=preview.targetOffset||{x:Math.sin(angle)*a.range*.65,z:Math.cos(angle)*a.range*.65};m.ring(p.x,.15,p.z,a.range,.025,'#625578');m.ring(p.x+o.x,.23,p.z+o.z,a.radius,.1,cancel?'#ff6c78':'#d2a6ff');m.disc(p.x+o.x,.19,p.z+o.z,.15,'#eedaff');}else if(a.aim==='cone')sector(p.x,p.z,angle,a.range,a.angle,cancel?'#592d39':'#695638');else if(a.aim==='radial')m.ring(p.x,.23,p.z,a.range,.07,col);else{const width=a.width||.6,fx=Math.sin(angle),fz=Math.cos(angle);for(const side of [-1,1])m.box(p.x+fx*a.range/2+fz*width*side,.2,p.z+fz*a.range/2-fx*width*side,.06,.015,a.range,col,angle);m.ring(p.x+fx*a.range,.2,p.z+fz*a.range,width,.07,col);}}
}
export class CombatHUD {
 constructor(){this.canvas=document.getElementById('combat-overlay');this.ctx=this.canvas.getContext('2d');}
 update(sim,camera,preview){const canvas=this.canvas,dpr=Math.min(devicePixelRatio||1,1.75),w=innerWidth,h=innerHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const c=this.ctx;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);c.textAlign='center';
 for(const t of [sim.player,...sim.targets]){const p=camera.project(t.x,3.05,t.z,w,h);c.fillStyle='#07141dda';c.fillRect(p.x-22,p.y,44,5);const ghost=sim.feedback?.states.get(t.id)?.ghost;if(ghost>t.health){c.fillStyle='#d2c2a3';c.fillRect(p.x-22,p.y,44*ghost/t.maxHealth,5);}const health=t.health/t.maxHealth;c.fillStyle=t.dead?'#4d5960':health<=.15?'#ff694f':health<=.3?'#edac55':t.team===1?'#65e4ca':'#ef8c9c';c.fillRect(p.x-22,p.y,44*t.health/t.maxHealth,5);c.fillStyle=t.team===1?'#65e4ca':t.team===2?'#ef8c9c':'#ccb16f';c.fillRect(p.x-25,p.y,2,5);c.font='bold 8px Arial';c.fillStyle='#f0eeee';c.fillText(sim.match?.protected(t)?'PROTECTED':t.dead?(Number.isFinite(t.respawnAt)?'RESPAWN '+Math.max(0,Math.ceil(t.respawnAt-sim.now)):'ELIMINATED'):hasStatus(t,'stun',sim.now)?'STUNNED':hasStatus(t,'slow',sim.now)?'SLOWED':t.name||(sim.definition.name||'KIT ASHER'),p.x,p.y-6);}
 sim.feedback?.drawHUD(c,camera,w,h);
 c.font='bold 17px Arial';for(const e of sim.effects.items)if(e.active&&e.type==='number'){const p=camera.project(e.x,2.8+(.85-(e.expires-sim.now))*1.8,e.z,w,h);c.strokeStyle='#15101c';c.lineWidth=3;c.strokeText(e.value,p.x,p.y);c.fillStyle='#ffd295';c.fillText(e.value,p.x,p.y);}
 for(const zone of sim.training.zones){const p=camera.project(zone.x,.15,zone.z,w,h);c.font='bold 11px Arial';c.fillStyle='#b5df99';c.fillText(sim.definition.id!=='kit-asher'?'WILDERNESS':zone.name,p.x,p.y);}
 document.getElementById('combat-status').textContent=sim.player.dead?(Number.isFinite(sim.player.respawnAt)?'RESPAWN '+Math.max(0,Math.ceil(sim.player.respawnAt-sim.now))+'s':'ELIMINATED · TEAM STILL FIGHTING'):`HP ${Math.ceil(sim.player.health)} / ${sim.player.maxHealth} · ${sim.inWilderness?'INNER FLAME +5%':'SPEED 100%'}`;
 document.getElementById('ember-streak').textContent=sim.definition.id==='riven'?`${sim.definition.stances[sim.stance].name.toUpperCase()} · ${sim.weapons.returning?'RETURNING':sim.stance==='reso'?(sim.weapons.next===2?'RECALL READY':('SCYTHE '+(sim.weapons.next+1))):'AREA CONTROL'}${sim.player.modifiers?.amp?.expires>sim.now?' · AMP '+Math.ceil(sim.player.modifiers.amp.expires-sim.now)+'s':''}`:sim.definition.id==='set'?`${sim.auraAllies.length?'PRESENCE · 2% MITIGATION':'PRESENCE · NO ALLIES'}${sim.player.modifiers?.warcry?.expires>sim.now?' · WAR CRY '+Math.ceil(sim.player.modifiers.warcry.expires-sim.now)+'s':''}`:`EMBER ${'●'.repeat(sim.streak)}${'○'.repeat(2-sim.streak)}${sim.streak===2?' · STUN READY':''}`;
 document.getElementById('combat-event').textContent=preview?.cancel?'Release to cancel':sim.lastEvent;
 const stats=sim.match?.actors.find(a=>a.sim===sim)?.record||sim.stats;document.getElementById('damage-total').textContent=`DAMAGE ${Math.round(stats.damage)} · KILLS ${stats.kills}`;
 }
}